### PR TITLE
Adding PostgreSQL 9.5

### PR DESCRIPTION
**Pull request by kennethgillen**
Adding PostgreSQL 9.5

### CODE REVIEW

**Comment by joshmoore** [comment]
Nice first step towards support :smile:

**Comment by kennethgillen** [comment]
Got to start somewhere.. ;)

**Comment by manics** [comment]
@kennethgillen Is this tested? If so can you cherry-pick https://github.com/openmicroscopy/infrastructure/pull/130/commits/963efbe57c69f320e9e1847bd657ec0ccf87b7eb otherwise `postgresql` is currently broken (see #130)

**Comment by kennethgillen** [comment]
@manics - no, not tested. I was looking at this in another context, to do with the repository and package names. Thought the repo names looked a bit odd. Just popped this in because it looked like a simple way to add the option, but I can just close the PR if we like.

**Comment by manics** [comment]
@up to you, but either this or #130 needs to be excluded

**Pull request closed without merging**
