### PR TITLE
Add some initial documentation for ansible

### PR DESCRIPTION
**Pull request by manics**
Some docs for discussion in next week's sysadmin/infrastructure/omero-deploy/docker meeting

### CODE REVIEW

**Comment by joshmoore** [comment]
Re: earlier conversation -- worth adding points re: "recommended-versions only", etc?

**Comment by manics** [comment]
Pushed

**Comment by joshmoore** [comment]
+1 thanks. Certainly a good starting point. How much feedback to you want pre-merging?

**Comment by manics** [comment]
If there's no pressure to merge at the moment you might as well give as much feedback as you want, and if/when it grows too much we can discuss.

**Pull request merged**
