### PR TITLE
Use OS_CLOUD env in dynamic inventory if set

### PR DESCRIPTION
**Pull request by manics**
`OS_CLOUD` is one of the standard os-client-config environment variables that can be used to select a single cloud with the openstack CLI e.g. `OS_CLOUD=omedev openstack server list`, but it's ignored by the `shade.inventory` module. This adds it to the dynamic openstack inventories so it can be used with ansible.

E.g. `OS_CLOUD=omedev ansible-playbook -i inventory/openstack.py playbook.yml`

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
all works great, the only thing is that inventory/openstack.py must replace https://github.com/openmicroscopy/management_tools/blob/master/ansible/inventory/openstack.py

**Comment by aleksandra-tarkowska** [comment]
@manics thanks for explanation :)

**Comment by aleksandra-tarkowska** [comment]
I am reverting my previous comment that all works ok.

I started from scratch and it looks like using openstack.py cause that vm is loosing attribute that determin host group

```
(dev_tools) MacBookPro:ansible ola$ OS_CLOUD=omedev ansible-playbook os-devspace.yml -e vm_name=ola-test -e vm_key_name=ola

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [fail] ********************************************************************
skipping: [localhost]

TASK [fail] ********************************************************************
skipping: [localhost]

TASK [Docker external access security group] ***********************************
ok: [localhost]

TASK [Docker external access security group rules] *****************************
ok: [localhost] => (item=22)
ok: [localhost] => (item=80)
ok: [localhost] => (item=443)
ok: [localhost] => (item=8443)
ok: [localhost] => (item=4444)
ok: [localhost] => (item=4063)
ok: [localhost] => (item=4064)
ok: [localhost] => (item=14063)
ok: [localhost] => (item=14064)

TASK [Docker VM] ***************************************************************
changed: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "IPs (Docker) private:192.168.1.96 floating:10.0.51.147"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=0   

(dev_tools) MacBookPro:ansible ola$ OS_CLOUD=omedev ansible-playbook  devspace.yml --list-hosts
statically included: /Users/ola/OMERO/SYSADMIN/management_tools/infrastructure/ansible/roles/devspace/tasks/devspace-install.yml

playbook: devspace.yml

  play #1 (devspace): devspace	TAGS: []
    pattern: [u'devspace']
    hosts (3):
      simon-devspace
      jm-viewer-1
      jm-viewer
```

any hint what am I missing?

**Comment by manics** [comment]
If you run with the new openstack.py but without setting `OS_CLOUD` does it work as before?

**Comment by aleksandra-tarkowska** [comment]
I am afraid it doesn't work

**Comment by manics** [comment]
and if you copy the old openstack.py over the new one it does work?

**Comment by aleksandra-tarkowska** [comment]
os-creation works only with https://github.com/openmicroscopy/management_tools/blob/master/ansible/inventory/openstack.py

installation works only with https://github.com/manics/infrastructure/blob/master/ansible/inventory/openstack.py

**Comment by aleksandra-tarkowska** [comment]
Following @manics suggestion about turning off cache I can confirm is working again

**Comment by joshmoore** [comment]
Merging then. Thanks guys.

**Pull request merged**
