### PR TITLE
ansible: devtoolset-4: Split installation into two steps

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Split up to allow installation in two steps.

### CODE REVIEW

**Comment by joshmoore** [comment]
Same problem:

```
PLAY [cowfish.openmicroscopy.org] **********************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************************************************************
ok: [cowfish.openmicroscopy.org]

TASK [devtoolset-4 : devtoolset-4 | Enable SCL repository] *********************************************************************************************************************************************************************************************************************
changed: [cowfish.openmicroscopy.org]

TASK [devtoolset-4 : devtoolset-4 | Install devtoolset-4] **********************************************************************************************************************************************************************************************************************
fatal: [cowfish.openmicroscopy.org]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'devtoolset-4' found available, installed or updated", "rc": 126, "results": ["No package matching 'devtoolset-4' found available, installed or updated"]}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************
cowfish.openmicroscopy.org : ok=2    changed=1    unreachable=0    failed=1
```

**Comment by rleigh-codelibre** [comment]
@joshmoore Thanks.  As suspected, the original task was file and this is functionally equivalent.

I suspect there's something about this host which needs tweaking independently; may be related to spacewalk?  Or a yum config change on the node iteself?  We probably made the same tweak to gretzky35, but I can't see any record of what that change was on the gdoc for gretzky35 or on trello.

@kennethgillen Any ideas what we might need to do here?

**Comment by rleigh-codelibre** [comment]
@joshmoore Would it be possible to retry with `-vvvv…` to see if it reports anything informative?

**Comment by joshmoore** [comment]
```
TASK [devtoolset-4 : devtoolset-4 | Enable SCL repository] 
changed: [cowfish.openmicroscopy.org] => {
    "changed": true,
    "changes": {
        "installed": [
            "centos-release-scl"
        ],
        "updated": []
    },
    "invocation": {
        "module_args": {
            "conf_file": null,
            "disable_gpg_check": false,
            "disablerepo": null,
            "enablerepo": null,
            "exclude": null,
            "install_repoquery": true,
            "installroot": "/",
            "list": null,
            "name": [
                "centos-release-scl"
            ],
            "skip_broken": false,
            "state": "latest",
            "update_cache": false,
            "validate_certs": true
        }
    },
    "msg": " Warning: Due to potential bad behaviour with rhnplugin and certificates, used slower repoquery calls instead of Yum API.",
    "rc": 0,
    "results": []
}
```

**Comment by kennethgillen** [comment]
@rleigh-codelibre can use infra-testpr to debug why this doesn't work on LSC-standard VM images.

**Comment by joshmoore** [comment]
Closing. Bug with spacewalk.

**Pull request closed without merging**
