### PR TITLE
IDR parent playbooks, reset passwords (IDR-0.3.0)

### PR DESCRIPTION
**Pull request by manics**
These are the top-level IDR deployment laybooks. Also resets the OMERO root password.

### CODE REVIEW

**Comment by manics** [comment]
Rebased

**Comment by joshmoore** [comment]
```
ERROR! the file_name '/home/travis/build/openmicroscopy/infrastructure/ansible/idr-playbooks/management.yml' does not exist, or is not readable
```

**Comment by manics** [comment]
That playbook is in https://github.com/openmicroscopy/infrastructure/pull/187
... which depends on https://github.com/openmicroscopy/infrastructure/pull/150

**Comment by joshmoore** [comment]
Re-opening for travis

**Comment by joshmoore** [comment]
Looks good & travis is green.

**Pull request merged**
