### PR TITLE
Allow to configure devspace checkout options and change default

### PR DESCRIPTION
**Pull request by sbesson**
As part of the work on the playbook refactoring, c829116 introduced options to force the update of the devspace. A side effect is that any redeployment of the devspace resets the CI space and makes the role effectively a provisioning playbook.

While we might want to clarify the separation between the provisioning and the deployment steps in the future, this commit should restore the default assumptions (i.e. redeploy only) and make the playbook idempotent by default. Force redeploying can be configured explicitly via the new devspace options.

/cc @joshmoore

### CODE REVIEW

**Comment by joshmoore** [comment]
Though not being able to easily test this at the moment, I'm in general for getting this in earlier rather than later.

**Comment by sbesson** [comment]
Having briefly tested with `-e devspace_git_update=true` after an initial deployment, I got

```
TASK [devspace : clone devspace] ***********************************************
fatal: [devspace-test]: FAILED! => {"before": "c66809d02e0a91c086ab2e957531eeb7dc85f112", "changed": false, "failed": true, "msg": "Local modifications exist in repository (force=no).", "warnings": []}
```

Given our current devspace workflow will create local modifications in the branch renaming step, we could merge the two new options into a single one for usability.

**Comment by sbesson** [comment]
Note while testing the devspace deployment with Ansible 2.2.0, I faced two issues in the devspace playbook:
- https://github.com/ansible/ansible-modules-core/issues/5504
- https://github.com/ansible/ansible/issues/18357

Downgraded Ansible to 2.1.3.0 in the meantime, I propose to update https://github.com/openmicroscopy/infrastructure/pull/231 accordingly.

**Comment by sbesson** [comment]
With Ansible 2.1.3.0 and shade 1.13.2, succesffully deployed https://10.0.51.132:8443/ via

```
$ ansible-playbook -l devspace-test -u centos devspace.yml 
```

See https://10.0.51.132:8443/job/BIOFORMATS-push/1 for the first run, redeploying the devspace with the same command leads to https://10.0.51.132:8443/job/BIOFORMATS-push/2. @joshmoore anything else you'd like to see tested before I try the new force/update options?

**Comment by joshmoore** [comment]
As long as there are local changes (`git status`) which persisted, then I'm good to merge.

**Comment by sbesson** [comment]
```
[omero@devspace-test devspace]$ git status
# HEAD detached at 0.3.4
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   bf/Dockerfile
#	modified:   home/jenkins.model.JenkinsLocationConfiguration.xml
#	modified:   home/jobs/BIOFORMATS-ant/config.xml
#	modified:   home/jobs/BIOFORMATS-maven/config.xml
#	modified:   home/jobs/BIOFORMATS-push/config.xml
#	modified:   home/jobs/OMERO-build/config.xml
#	modified:   home/jobs/OMERO-push/config.xml
#	modified:   home/jobs/OMERO-robot/config.xml
#	modified:   nginx/Dockerfile
#	modified:   server/Dockerfile
#	modified:   slave/Dockerfile
#	modified:   web/Dockerfile
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	bf/.jenkins/
no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by joshmoore** [comment]
:+1:

**Pull request merged**
