### PR TITLE
ice 3.6.3

### PR DESCRIPTION
**Pull request by jburel**
Bump ice version and download rpm
unfortunately the previous approach does not work.
tested via https://ci.openmicroscopy.org/view/Mgmt/job/ICE-centos6-archive/33/

### CODE REVIEW

**Comment by manics** [comment]
Since docker let's us setup individual test environments could we get rid of the whole multi-ice package?

**Comment by jburel** [comment]
Maybe after the release we could look into that, release is fast approaching and probably better to follow a workflow that worked for us before.

**Comment by manics** [comment]
Ice 3.6 uses a different installation procedure for Python (pip instead of rpm), so I so think the old workflow would require modification anyway.

**Comment by jburel** [comment]
I know, Let's discuss tomorrow. trying to minimise the changes.

**Comment by jburel** [comment]
This is the approach I had to take due to a change on zeroc side. Will recheck post release if it is still necessary. ice 3.6.2 has been deployed on the nodes using the management job.

**Comment by joshmoore** [comment]
Any reason not to merge, @jburel ?

**Comment by jburel** [comment]
Before merging I might try to see if they have fixed the issue encountered at the time with zeroc website so we don't have to do ``wget`` for all the dependencies

**Comment by jburel** [comment]
No luck, Something has changed on their site.
So we will have to use the change made in this PR

**Comment by joshmoore** [comment]
Checking if this is tested regularly by a merge job.

**Comment by joshmoore** [comment]
Job is pointing to J-m's repo. Suggest merging and updating the job.

**Comment by sbesson** [comment]
To be reconsidered as part of the Ice 3.6.3 testing epic.

**Comment by jburel** [comment]
bump to 3.6.3, still have to be download the rpm one at a time

**Comment by jburel** [comment]
tested via https://ci.openmicroscopy.org/view/Mgmt/job/ICE-centos6-archive/40/

**Comment by sbesson** [comment]
To be merged once the corresponding code PR is included into the OMERO code.

**Comment by joshmoore** [comment]
No vetoes.

**Pull request merged**
