### PR TITLE
Docker node roles

### PR DESCRIPTION
**Pull request by manics**
Includes
- docker-storage for setting up the docker thin partitions
- docker for setting up docker including groups
- lvm-partition as a generic role for creating any LVM storage partition
- role for installing samba-clients

Also separate playbooks for provisioning (setting up hardware) and deploying (everything else which doesn't involve hardware configuration)

Note the generic `lvm-partition` role could be used to replace the `jenkinsslave-storage` role in a future PR.

### CODE REVIEW

**Comment by joshmoore** [comment]
Currently testing `ansible-playbook -i testpr --step infrastructure/ansible/idr-provision.yml` :smile:

**Comment by manics** [comment]
if you manage to get through `idr-deployment.yml` you should be able to test the local dns server by querying the host directly (`dig SRV \*.whatever.domain.you.configured @docker-hostname`)

**Comment by joshmoore** [comment]
Do I need provision before deployment?

It's clear that without enough fiddling it likely *would* work. I removed network role (for obvious reasons). Copying `host_vars/narwhal` to `host_vars/infra-testpr` got me to:

```
(venv)[jamoore@ome-c6100-3 ansible]$ ansible-playbook -i testpr --step infrastructure/ansible/idr-provision.yml

PLAY [idr-docker] *************************************************************

GATHERING FACTS ***************************************************************
ok: [infra-testpr]
Perform task: lvm-partition | storage | create logical volume (y/n/c): y

Perform task: lvm-partition | storage | create logical volume (y/n/c):  *******
failed: [infra-testpr] => {"failed": true}
```

**Comment by manics** [comment]
At the moment yes (because it uses a custom lvm partition), I was just debating whether to add some default vars so that it'd work without the provision step. Shouldn't be too difficult but I didn't want to inadvertently break this PR

**Comment by joshmoore** [comment]
Happy for this to be merged as is a la a snapshot of the current state and I'll look at subsequent PRs.

**Comment by manics** [comment]
No-one else has objected, merging so we can use some of these roles in other PRs.

**Pull request merged**
