### PR TITLE
Improve doc ci node

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
add missing package(s):

- add `Pygments`, doc prerequisites
- add `ansible`, omeroweb-install prerequisites

see https://ci.openmicroscopy.org/job/TEST-DEV-merge-docs and https://ci.openmicroscopy.org/job/TEST-DEV-merge-docs-autogen

keep in mind https://github.com/openmicroscopy/infrastructure/pull/20

### CODE REVIEW

**Comment by sbesson** [comment]
As briefly mentioned yesterday, I think a series of next steps would be:
- remove `epydoc` (fully replaced by Sphinx to generate the Python API doc)
- make the `texlive` role optional and/or remove the role in the context of https://trello.com/c/SnUesylG/505-ditching-docs-pdfs
- refactor the Sphinx dependency handling out of `jenkinsslave` into a separate role. A constraint of the current docs build logic is the Sphinx + Ant dependency. In the context of building docs via Jenkins, this means we would either need Ant installed in the role (as proposed in the role https://github.com/openmicroscopy/infrastructure/pull/20), or Sphinx installed globally instead of using a virtualenv or some code work to remove this dependency.

**Comment by manics** [comment]
> this means we would either need Ant installed in the role (as proposed in the role #20), or Sphinx installed globally instead of using a virtualenv or some code work to remove this dependency.

If we're moving to more compartmentalised build servers e.g. a docker container or VM that only builds docs everything could be installed at the global level if that makes things easier

**Comment by aleksandra-tarkowska** [comment]
My intention is only to move away doc jobs from cowfish as server was overloaded. If we would like to do more complex rearrangement of the roles, maybe we could handle that separately. As the pdf removal decision hasn't been made. I could wait for @rleigh-codelibre return to help with fixing `texlive`

**Comment by joshmoore** [comment]
spider-5 is now created:

```
[hudson@spider-5 ~]$ ./virtualenv/bin/pip freeze | grep Pyg
Pygments==1.4
[hudson@spider-5 ~]$ which ansible
/bin/ansible
```

I'm merging this and will open a doc PR against MT.

**Comment by joshmoore** [comment]
NB: I assume it's possible to test moving PRs to this jenkins node.

**Pull request merged**
