### PR TITLE
Add external munin roles (IDR-0.3.0)

### PR DESCRIPTION
**Pull request by manics**
Adds `munin` (server) and `munin-node` (client) roles using `ansible-galaxy install -r requirements.yml`.

`ansible/vendor/` is configured as the location for external roles.

~~These  commits were obtained by running `git filter-branch` to move the files/commits from:~~
~~- https://github.com/manics/ansible-role-munin (upstream https://github.com/geerlingguy/ansible-role-munin)~~
~~- https://github.com/manics/ansible-role-munin-node (upstream https://github.com/geerlingguy/ansible-role-munin-node)~~

~~into `ansible/vendor/`:~~

~~#### ansible-role-munin~~
~~`git filter-branch -f --tree-filter 'for f in .travis.yml README.md defaults files meta tasks templates tests vars; do mkdir -p ansible/vendor/munin; test -e $f && mv $f ansible/vendor/munin/; done'`~~

~~#### ansible-role-munin-node~~
~~`git filter-branch -f --tree-filter 'for f in .gitignore .travis.yml README.md defaults handlers meta tasks templates tests vars; do mkdir -p ansible/vendor/munin-node; test -e $f && mv $f ansible/vendor/munin-node/; done'`~~

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by joshmoore** [comment]
Mentioned to @manics, I'd probably err on the side of requirements.yml rather than a submodule, but could use other's opinions: @kennethgillen @aleksandra-tarkowska @sbesson

**Comment by sbesson** [comment]
Two quick comments:
- this effectively introduces a second nested layer of submodules (as infrastructure is included as a submodule of `management_tools`). As far as I know, this is something we have never dealt with this and it is likely this might require work on some of the tooling/workflow/training.
- generally, I don't think we want to point to a personal repository from an organization repository. Is there a plan to migrate the munin roles to the organization at some point?

**Comment by manics** [comment]
> generally, I don't think we want to point to a personal repository from an organization repository. Is there a plan to migrate the munin roles to the organization at some point?

Yes, it's a fork of another repo so I had to fork it into my own user.

**Comment by joshmoore** [comment]
Is this off-hold now? i.e. we can make decisions and get it in?

**Comment by manics** [comment]
Force pushed, added https://github.com/manics/ansible-role-munin.git and https://github.com/manics/ansible-role-munin-node.git using `git read-tree`Force pushed, added https://github.com/manics/ansible-role-munin.git and https://github.com/manics/ansible-role-munin-node.git using `git read-tree`

**Comment by joshmoore** [comment]
Probably needs a general agreement from @openmicroscopy/devops

**Comment by manics** [comment]
--exclude

**Comment by manics** [comment]
I've force pushed using a new strategy described in the description.

**Comment by manics** [comment]
A playbook requiring these nodes is in https://github.com/openmicroscopy/infrastructure/pull/187

**Comment by manics** [comment]
Force pushed again, this time using requirements.yml

**Comment by manics** [comment]
I've switched to using `https://github.com/openmicroscopy/ansible-role-munin{,-node}.git`

We could leave the tagging discussion for later?

**Comment by joshmoore** [comment]
Merging to make progress on the other currently open PRs. Would be good to get tags in place for the overall 0.3.0 tag though.

**Pull request merged**
