### PR TITLE
Update omero-web-apps role, update mapr (IDR-0.3.1)

### PR DESCRIPTION
**Pull request by manics**
~~This includes https://github.com/openmicroscopy/infrastructure/pull/220 to avoid conflicts when cherry-picking.~~

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1127](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1127/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1127/consoleText) for more details.
Possible conflicts:
  - PR #220 manics 'Install JDK on idr OMERO for jstack (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml
  - PR #222 manics 'Bump IDR omero to 0.3.1-rc2, and idr-notebooks to HEAD (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1128](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1128/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1128/consoleText) for more details.
Possible conflicts:
  - PR #220 manics 'Install JDK on idr OMERO for jstack (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml
  - PR #222 manics 'Bump IDR omero to 0.3.1-rc2, and idr-notebooks to HEAD (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1129](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1129/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1129/consoleText) for more details.
Possible conflicts:
  - PR #220 manics 'Install JDK on idr OMERO for jstack (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml
  - PR #222 manics 'Bump IDR omero to 0.3.1-rc2, and idr-notebooks to HEAD (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1130](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1130/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1130/consoleText) for more details.
Possible conflicts:
  - PR #220 manics 'Install JDK on idr OMERO for jstack (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml
  - PR #222 manics 'Bump IDR omero to 0.3.1-rc2, and idr-notebooks to HEAD (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1131](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1131/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1131/consoleText) for more details.
Possible conflicts:
  - PR #220 manics 'Install JDK on idr OMERO for jstack (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml
  - PR #222 manics 'Bump IDR omero to 0.3.1-rc2, and idr-notebooks to HEAD (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1132](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1132/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1132/consoleText) for more details.
Possible conflicts:
  - PR #220 manics 'Install JDK on idr OMERO for jstack (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml
  - PR #222 manics 'Bump IDR omero to 0.3.1-rc2, and idr-notebooks to HEAD (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1133](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1133/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1133/consoleText) for more details.
Possible conflicts:
  - PR #220 manics 'Install JDK on idr OMERO for jstack (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml
  - PR #222 manics 'Bump IDR omero to 0.3.1-rc2, and idr-notebooks to HEAD (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1134](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1134/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1134/consoleText) for more details.
Possible conflicts:
  - PR #220 manics 'Install JDK on idr OMERO for jstack (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml
  - PR #222 manics 'Bump IDR omero to 0.3.1-rc2, and idr-notebooks to HEAD (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1135](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1135/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1135/consoleText) for more details.
Possible conflicts:
  - PR #220 manics 'Install JDK on idr OMERO for jstack (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml
  - PR #222 manics 'Bump IDR omero to 0.3.1-rc2, and idr-notebooks to HEAD (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1136](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1136/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1136/consoleText) for more details.
Possible conflicts:
  - PR #220 manics 'Install JDK on idr OMERO for jstack (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml
  - PR #222 manics 'Bump IDR omero to 0.3.1-rc2, and idr-notebooks to HEAD (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1137](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1137/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1137/consoleText) for more details.
Possible conflicts:
  - PR #220 manics 'Install JDK on idr OMERO for jstack (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml
  - PR #222 manics 'Bump IDR omero to 0.3.1-rc2, and idr-notebooks to HEAD (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1138](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1138/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1138/consoleText) for more details.
Possible conflicts:
  - PR #220 manics 'Install JDK on idr OMERO for jstack (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml
  - PR #222 manics 'Bump IDR omero to 0.3.1-rc2, and idr-notebooks to HEAD (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1139](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1139/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1139/consoleText) for more details.
Possible conflicts:
  - PR #220 manics 'Install JDK on idr OMERO for jstack (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml
  - Upstream changes
    - ansible/idr-playbooks/group_vars/omero-hosts.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1140](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1140/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1140/consoleText) for more details.
Possible conflicts:
  - PR #220 manics 'Install JDK on idr OMERO for jstack (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml
  - Upstream changes
    - ansible/idr-playbooks/group_vars/omero-hosts.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1141](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1141/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1141/consoleText) for more details.
Possible conflicts:
  - PR #220 manics 'Install JDK on idr OMERO for jstack (IDR-0.3.1)'
    - ansible/idr-playbooks/group_vars/omero-hosts.yml
  - Upstream changes
    - ansible/idr-playbooks/group_vars/omero-hosts.yml

**Comment by manics** [comment]
Rebased

**Comment by joshmoore** [comment]
ome101 run passing. Merging for a final test of origin/master

**Pull request merged**
