### PR TITLE
install redis

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
Install redis on Cowfish

```
[omero@bea7970cf861 ~]$ redis-cli
127.0.0.1:6379> ping
PONG
127.0.0.1:6379> 
```

test using https://github.com/ome/ome-docker/pull/34

### CODE REVIEW

**Comment by joshmoore** [comment]
btw, see https://github.com/joshmoore/management_tools/commit/aeb70a46d8ae7447cb117180594ae69196b48125 on https://github.com/joshmoore/management_tools/tree/samba-test for setting up a test for ansible PRs.

**Comment by joshmoore** [comment]
@aleksandra-tarkowska : can you please fast-forward this branch to https://github.com/joshmoore/infrastructure/commit/e547a3eb19e65a88fd39ea2a34b1d9703eb44cc3

**Comment by joshmoore** [comment]
With that commit, I successfully tested on mini4:

```
mini4                      : ok=4    changed=2    unreachable=0    failed=0

~/opt/management_tools $ ansible-playbook -i ansible/idr/prod-hosts infrastructure/ansible/idr-services.yml -l mini4

PLAY ***************************************************************************
skipping: no hosts matched

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [mini4]

TASK [redis : system packages | install epel repo] *****************************
ok: [mini4]

TASK [redis : install redis] ***************************************************
changed: [mini4]

TASK [redis : set redis to start on startup] ***********************************
changed: [mini4]

PLAY RECAP *********************************************************************
mini4                      : ok=4    changed=2    unreachable=0    failed=0

~/opt/management_tools $ ansible-playbook -i ansible/idr/prod-hosts infrastructure/ansible/idr-services.yml -l mini4 -C

PLAY ***************************************************************************
skipping: no hosts matched

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [mini4]

TASK [redis : system packages | install epel repo] *****************************
ok: [mini4]

TASK [redis : install redis] ***************************************************
ok: [mini4]

TASK [redis : set redis to start on startup] ***********************************
ok: [mini4]

PLAY RECAP *********************************************************************
mini4                      : ok=4    changed=0    unreachable=0    failed=0

```

**Comment by manics** [comment]
Can you add a README?

**Comment by joshmoore** [comment]
:thumbsup:

**Comment by joshmoore** [comment]
I'll test in/with https://github.com/openmicroscopy/infrastructure/pull/70

**Pull request merged**
