### PR TITLE
IDR about deployment page

### PR DESCRIPTION
**Pull request by manics**
This moves the former README-os-idr.md into `idr-playbooks/files/html` and adds a HTML, wrapper so it appears alongside the current `/about` page. I've updated the file to correspond to the latest IDR deployment playbooks, and added some background information.

### CODE REVIEW

**Comment by manics** [comment]
Just put this on-hold....we forgot to discuss it in the last IDR meeting

**Comment by manics** [comment]
This needs discussion since it's included in the intended IDR deployment branch https://github.com/openmicroscopy/infrastructure/pull/159 If we don't want a deployment doc alongside the about page I'll remove it.

**Comment by manics** [comment]
Last commit adds a link to `/jupyter`

**Comment by joshmoore** [comment]
I've manually copied the state as of https://github.com/openmicroscopy/infrastructure/pull/154/commits/69baf1b326ba49835d06bc380baa1e90e7d553ac to the new repo. Happy for this to go in as the current (0.3.0-rc2) way of deploying; or happy to move straight to use of jekyll-playbooks.

**Comment by manics** [comment]
I'll merge then.

**Pull request merged**
