### PR TITLE
Add haproxy to requirements.yml, add example (IDR-0.3.1)

### PR DESCRIPTION
**Pull request by manics**
This depends on https://github.com/openmicroscopy/ansible-role-haproxy.git which doesn't currently exist, so for initial testing you'll have to change that line in `requirements.yml` to https://github.com/manics/ansible-role-haproxy (currently in process of being transferred to @joshmoore)

### CODE REVIEW

**Comment by joshmoore** [comment]
Transferred to https://github.com/openmicroscopy/ansible-role-haproxy

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1096](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1096/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1096/consoleText) for more details.
Possible conflicts:
  - PR #174 jburel 'Scripts role'
    - ansible/Vagrantfile
  - PR #196 manics 'Add Vagrantfile for IDR (IDR-0.3.0)'
    - ansible/Vagrantfile

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1097](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1097/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1097/consoleText) for more details.
Possible conflicts:
  - PR #174 jburel 'Scripts role'
    - ansible/Vagrantfile
  - PR #196 manics 'Add Vagrantfile for IDR (IDR-0.3.0)'
    - ansible/Vagrantfile

**Comment by joshmoore** [comment]
Closing until 174 and 196 are cleared up. If may have some commits of my own, in which case I'll just open a new PR.

**Comment by joshmoore** [comment]
Note: from my side, happy for this to go in as soon as conflicts are resolved.

**Pull request closed without merging**
