### PR TITLE
upgrade django-redis

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
When using redis we have to use newer supported package https://trello.com/c/GIJQA0kg/177-redis-out-of-experimental

### CODE REVIEW

**Comment by manics** [comment]
Seems to work on the IDR

```
[spli@demo3c-omero ~]$ pip freeze |grep redis
You are using pip version 7.1.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
django-redis==4.5.0
redis==2.10.3
```

**Comment by aleksandra-tarkowska** [comment]
did you `yum install python-redis`?

**Comment by manics** [comment]
Yes, it's installed but it doesn't show up in `pip freeze`
```
[spli@demo3c-omero ~]$ rpm -qa \*redis\*
python-redis-2.10.3-1.el7.noarch
redis-2.8.19-2.el7.x86_64
```

**Comment by joshmoore** [comment]
No vetoes.

**Pull request merged**
