### PR TITLE
Web proxy setup

### PR DESCRIPTION
**Pull request by manics**
- Change ci-initial.yml to ansible/all-initial.yml, and apply to `all`, so it can be used for setting up any new server.
- Change `idr-services.yml` to expand root and log volumes

### CODE REVIEW

**Comment by joshmoore** [comment]
Barring

```
ERROR! the file_name '/home/travis/build/openmicroscopy/infrastructure/ansible/ci-initial.yml' does not exist, or is not readable
```

this looks good. (Tested a `-C` run locally with ansible 2.1 which handled LVM much better.)

**Comment by manics** [comment]
The problem now is
```
$ ansible-playbook -i ansible/example-hosts --syntax-check ansible/*.yml
ERROR! vars file vars/os-create-{{ os_cloud_provider | default('uod') }}.yml was not found
```

**Comment by joshmoore** [comment]
Is there a fix for that?

**Comment by manics** [comment]
Not without refactoring the playbooks, it looks like you can't have a conditional (`when:`) in `vars_files`

**Comment by joshmoore** [comment]
Then exclude this playbook from travis?

**Comment by manics** [comment]
I've just found this https://github.com/ansible/ansible/issues/10010#issuecomment-70647392
Not quite the same behaviour (since it'll also default to `-uod` if `os_cloud_provider` is invalid instead of only when it's empty)

**Comment by manics** [comment]
Pushed, see the commit message for caveats

**Comment by joshmoore** [comment]
No possibility of a `noop.yml`? If not, let's go with this, and we can see how often it bites us.

**Comment by manics** [comment]
I could do that, but it means `os_cloud_provider` becomes mandatory whereas previously it defaults to `uod`. Reckon it's worth it?

**Comment by joshmoore** [comment]
Hmmm.....don't know. Let's hold off and see.

**Pull request merged**
