### PR TITLE
Remove old docker roles

### PR DESCRIPTION
**Pull request by manics**
The one server that used to use the old `docker-{advanced,storage}` roles has been upgraded to the new `docker` role.

Ideally `idr-docker-old.yml` would be subsumed by `idr-docker-localstorage.yml`, but due to a different LVM configuration on the old servders this isn't possible.

### CODE REVIEW

**Comment by joshmoore** [comment]
> Ideally idr-docker-old.yml would be subsumed by idr-docker-localstorage.yml, but due to a different LVM configuration on the old servders this isn't possible.

So once we re-image narwhal this can be deleted?

**Comment by joshmoore** [comment]
Running a local `-C` version against idr-hosts passes (all green).

**Comment by manics** [comment]
> So once we re-image narwhal this can be deleted?

Yes

**Comment by joshmoore** [comment]
:+1:

**Pull request merged**
