### PR TITLE
web app build role

### PR DESCRIPTION
**Pull request by jburel**
Add role to install node and grunt-cli

I have added the main and an redhat yml files
planning to add when things are sorted a debian one (in another PR)

### CODE REVIEW

**Comment by joshmoore** [comment]
Pointed @jburel at http://stackoverflow.com/a/36656334 for skipping in check_mode. @manics: this our "official" way of skipping tasks?

**Comment by manics** [comment]
@joshmoore I haven't tried `ansible_check_mode`, but looks fine.

**Comment by manics** [comment]
Just had a discussion with @jburel. The problem with using `ansible_check_mode` to bypass a task which depends on an executable installed by a preceding task is that it's not obvious to subsequent roles/tasks.

For example, if a later task/role assumes npm is installed and installs a module, then in check-mode that role would fail instead of the original.

**Comment by jburel** [comment]
new role used to install on cowfish
``
[jburel@cowfish ~]$ node --version
v6.9.1
[jburel@cowfish ~]$ grunt --version
grunt-cli v1.2.0
``

**Comment by aleksandra-tarkowska** [comment]
any thoughts why figure is failing?

```
setuptools, tokenize;__file__='/tmp/pip-build-BvPaKT/omero-figure/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-t7_tL7-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/hudson/workspace/WEB-DEV-trial-deploy/trial-venv/include/site/python2.7/omero-figure:
    running install
    running grunt
    grunt jst
    grunt-cli: The grunt command line interface (v1.2.0)
    
    Fatal error: Unable to find local grunt.
    
    If you're seeing this message, grunt hasn't been installed locally to
    your project. For more information about installing and configuring grunt,
    please see the Getting Started guide:
    
    http://gruntjs.com/getting-started
    error: command 'grunt' failed with exit status 99
```

**Comment by jburel** [comment]
I see. I will look at it post release

**Comment by jburel** [comment]
we might have to re-add ``npm install`` step in the figure PR, will test later on

**Comment by jburel** [comment]
This role works correctly.
We will probably be looking into unifying the way the web app are built so ``grunt-cli`` might no be required.
https://github.com/ome/omero-figure/pull/188 is currently excluded

**Comment by jburel** [comment]
Figure installation now works so we will keep ``grunt-cli`` i.e. we won't be unifying this round the build system

**Comment by jburel** [comment]
role has been used and tested to deploy on cowfish and spider-x

**Comment by manics** [comment]
I haven't tested this but the code looks fine

**Comment by joshmoore** [comment]
Thanks. Merging. @jburel: if you want to attempt extracting as a separate role see, https://github.com/openmicroscopy/infrastructure-extract-ansible-role/

**Comment by kennethgillen** [comment]
General note - node is offered by epel, and another repo was added by this role. Caused dependency issues patching cowfish, bypassed by excluding `node` from the updates.

**Comment by jburel** [comment]
@kennethgillen it is available but we need node 6 minimum for iviewer
that's why another repo is used

**Comment by joshmoore** [comment]
Is there a suggested change here?

**Comment by jburel** [comment]
I will see if I can find an alternative since epel 7 should be updated to 6.x

**Comment by jburel** [comment]
PR opened https://github.com/openmicroscopy/infrastructure/pull/253 to install from epel-testing

**Pull request merged**
