### PR TITLE
Backwards-compatible requirements for galaxy roles

### PR DESCRIPTION
**Pull request by manics**
## `requirements.yml`
This is the recommended requirements file. New playbooks should use only this, existing playbooks should be migrated to use only this.

## `requirements-compat.yml`
Install this in addition to `requirements.yml` to run existing playbooks.

## Other changes
- The travis script commands have been moved into a separate file.
- `os-idr-playbooks` have been removed (replaced by https://github.com/IDR/deployment/)
---
Background: https://github.com/openmicroscopy/infrastructure/pull/245#pullrequestreview-19041598

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1233](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1233/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1233/consoleText) for more details.
Possible conflicts:
  - PR #245 aleksandra-tarkowska 'Devspace docker issues'
    - ansible/requirements.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1234](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1234/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1234/consoleText) for more details.
Possible conflicts:
  - PR #245 aleksandra-tarkowska 'Devspace docker issues'
    - ansible/requirements.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1235](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1235/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1235/consoleText) for more details.
Possible conflicts:
  - PR #245 aleksandra-tarkowska 'Devspace docker issues'
    - ansible/requirements.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1236](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1236/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1236/consoleText) for more details.
Possible conflicts:
  - PR #245 aleksandra-tarkowska 'Devspace docker issues'
    - ansible/requirements.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1237](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1237/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1237/consoleText) for more details.
Possible conflicts:
  - PR #245 aleksandra-tarkowska 'Devspace docker issues'
    - ansible/requirements.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1238](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1238/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1238/consoleText) for more details.
Possible conflicts:
  - PR #245 aleksandra-tarkowska 'Devspace docker issues'
    - ansible/requirements.yml

**Comment by aleksandra-tarkowska** [comment]
works as expected with https://github.com/openmicroscopy/infrastructure/pull/245

**Comment by joshmoore** [comment]
@aleksandra-tarkowska : how do you want to handle the conflict here? Get this PR in before 245?

**Comment by aleksandra-tarkowska** [comment]
I removed conflicting commit https://ci.openmicroscopy.org/view/Mgmt/job/MANAGEMENT_TOOLS-merge/1239/console, please merge this one first anyway

**Pull request merged**
