### PR TITLE
Sphinx build role

### PR DESCRIPTION
**Pull request by sbesson**
This is a minimal port of the changes proposed https://github.com/openmicroscopy/infrastructure/pull/20 in the context of the upcoming Bio-Formats 5.3.0-m1 release preparation.

This PR puts the minimal requirements into place for documentation nodes, i.e. installing Sphinx as a dependency. As discussed previously, Sphinx is installed globally instead of within a virtual environment to allow it to be consumed by the Jenkins Ant targets which cannot activate a virtual environment. It also applies the policy of dropping the PDF in favor of ZIPs of the HTML and removes the `texlive` step from the `ci-deployment` playbook. /cc @jburel

### CODE REVIEW

**Comment by sbesson** [comment]
As discussed the last couple of commits should add a minimal Vagrant test for the `sphinx` role. It helps me realize the missing Python dependencies on the role. Looking into the repo, I decided to reuse `python-devel`. Two comments proposals on this role:

-  81c3243 removes the `gcc` dependency but this could be moved to a separate PR (I could only find `qa-web-deployment.yml` using this role and this playbook has not been tested for a year
- I would propose to rename the role in a separate to something more generic that does not clash with one of the packages installed e.g. `base-python-deps`, `pythondeps`
- once the base python dependency role is sorted, we could likely refactor a number of roles which each reinstall these dependencies and make them use the base role

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1053](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1053/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1053/consoleText) for more details.
Possible conflicts:
  - PR #152 manics 'New role to hide SELinux issues'
    - ansible/test.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#1054](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1054/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/1054/consoleText) for more details.
Possible conflicts:
  - PR #152 manics 'New role to hide SELinux issues'
    - ansible/test.yml

**Comment by joshmoore** [comment]
LGTM. @manics: you ok with this going in first?

**Comment by joshmoore** [comment]
Sorry, @sbesson. While waiting I reviewed selinux and it was ready to go. Can you merge/rebase?

**Comment by sbesson** [comment]
@joshmoore pushed.

**Comment by joshmoore** [comment]
```
TASK [command] *****************************************************************
changed: [docs] => {"changed": true, "cmd": ["sphinx-build", "--version"], "delta": "0:00:00.158925", "end": "2016-11-04 15:30:07.633216", "rc": 0, "start": "2016-11-04 15:30:07.474291", "stderr": "", "stdout": "Sphinx (sphinx-build) 1.2.3", "stdout_lines": ["Sphinx (sphinx-build) 1.2.3"], "warnings": []}

TASK [assert] ******************************************************************
ok: [docs] => {"changed": false, "msg": "all assertions passed"}

PLAY RECAP *********************************************************************
docs                       : ok=7    changed=5    unreachable=0    failed=0
```

:+1:

**Pull request merged**
