### PR TITLE
Update exe4j version

### PR DESCRIPTION
**Pull request by dominikl**
Use the latest version 6 of exe4j to support Java 9.

Test: Check Importer and/or Insight exe on Windows with Java 9 installed.

### CODE REVIEW

**Comment by joshmoore** [comment]
So proposing to run this on eel & seabass?

**Comment by joshmoore** [comment]
Ok. Making some progress, but not currently in a great state.

(1) Took me a while to realize that check mode wasn't going to do anything for this task:

```
skipping: [octopus.openmicroscopy.org] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "_raw_params": "exe4jc -L=\"...\""
        }
    },
    "msg": "remote module (command) does not support check mode"
}
```

(2) For eel/octopus, `exe4jc` is not on the `$PATH`:

```
TASK [omero-build : exe4j packages | install license] *********************************************************************************
fatal: [octopus.openmicroscopy.org]: FAILED! => {"changed": false, "cmd": "exe4jc '-L=...'", "msg": "[Errno 2] No such file or directory", "rc": 2}
```

(3) Hard-coding it for the moment, it's failing to find Java:

```
TASK [omero-build : exe4j packages | install license] *********************************************************************************
fatal: [octopus.openmicroscopy.org]: FAILED! => {"changed": true, "cmd": ["/opt/exe4j/bin/exe4jc", "-L=..."], "delta": "0:00:01.791296", "end": "2018-02-12 16:29:12.976658", "msg": "non-zero return code", "rc": 83, "start": "2018-02-12 16:29:11.185362", "stderr": "", "stderr_lines": [], "stdout": "No suitable Java Virtual Machine could be found on your system.\nThe version of the JVM must be 1.8.\nPlease define INSTALL4J_JAVA_HOME to point to a suitable JVM.", "stdout_lines": ["No suitable Java Virtual Machine could be found on your system.", "The version of the JVM must be 1.8.", "Please define INSTALL4J_JAVA_HOME to point to a suitable JVM."]}
```

**Comment by joshmoore** [comment]
So hard-coding to the Hudson installed JDK8 has us registered:

```
[jamoore@ome-c6100-1 bin]$ export PATH=/opt/hudson/tools/hudson.model.JDK/8_LATEST/bin/:$PATH
[jamoore@ome-c6100-1 bin]$ ./exe4jc --version
exe4j version 6.0 (build 6020), built on 2017-07-13
```

I'll need to push a few changes to make this runnable by others.

**Comment by joshmoore** [comment]
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-build/891/ is currently testing whether the deployment of the 6.0 version is functional.

**Comment by joshmoore** [comment]
insight opens fine on mac.

**Comment by joshmoore** [comment]
Last commit worked against octopus with: 

```
ansible-playbook ci-deployment.yml -t exe4j -i ../../ansible/inventory/ci-hosts -l octopus.openmicroscopy.org --diff --ask-become
```

Task was critical since octopus was not previously a managed CI server:

```
diff --git a/ansible/inventory/ci-hosts b/ansible/inventory/ci-hosts
index e130cbf..719339e 100644
--- a/ansible/inventory/ci-hosts
+++ b/ansible/inventory/ci-hosts
@@ -51,6 +51,7 @@ seabass.openmicroscopy.org
 # nodes which build OMERO
 [ci-omero]
 seabass.openmicroscopy.org
+octopus.openmicroscopy.org
```

**Comment by dominikl** [comment]
Thanks Josh for figuring that out. And I thought initially this is just gonna be a matter of a simple string replace 5_0_1 with 6_0 ... :-)

**Comment by sbesson** [comment]
Overall :+1: for getting these changes deployed with the JDK build requirements.

**Comment by joshmoore** [comment]
Discussed with @jburel @dominikl and @sbesson : 

 * After failure of `OMERO-DEV-latest-submods`, that job has been moved to use JDK8
 * Assumption is that the only impact the change will have is on `build_time && exe4j_installed && jdk <= 7` (which seems remote enough to not worry about).
 * We're *not* updating seabass since it no longer has builds that use exe4j.

Merging this and I'll open a MT Pr with the octopus setting.

**Pull request merged**
