### PR TITLE
Add mtu override to docker, remove distro docker support

### PR DESCRIPTION
**Pull request by manics**
Everything up to https://github.com/openmicroscopy/infrastructure/commit/5c0acef2de23af398a91894184dd35d82db84498 changes this role to use upstream docker instead of supporting upstream and the distribution version, since we never use the latter.

The remaining commits add support for setting the Docker MTU from the default NIC instead of using auto-discovery which may not work.
- https://github.com/docker/docker/issues/22028
- https://github.com/docker/docker/pull/18108
- https://github.com/docker/docker/issues/12565

Docker 1.9 used the MTU of the default network route/NIC, which may be lower than the typical 1500 on VMs using virtual networking (tunnelling). Docker 1.10+ attempts to use Path MTU Discovery to find out the correct MTU for a route. Unfortunately this appears to be broken when bridges and/or tunneling is involved. Suggested fix is to define the MTU when starting the docker daemon. No idea why docker sometimes still works in a VM without the fix.

### CODE REVIEW

**Comment by manics** [comment]
The last commit https://github.com/openmicroscopy/infrastructure/pull/67/commits/7bcbc81b7e6ee29add95d6213a32f9e1f9f166e9 modifies the systemd service file to include the changes with the most recent docker release (1.11.0).

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#636](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/636/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/636/consoleText) for more details.
Possible conflicts:
  - PR #64 joshmoore 'docker: add docker-compose installation to the role'
    - ansible/roles/docker/tasks/docker-common.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#637](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/637/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/637/consoleText) for more details.
Possible conflicts:
  - PR #64 joshmoore 'docker: add docker-compose installation to the role'
    - ansible/roles/docker/tasks/docker-common.yml

**Comment by manics** [comment]
`openstack/examples/omedev-docker.yml` moved to this PR from #61

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#638](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/638/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/638/consoleText) for more details.
Possible conflicts:
  - PR #64 joshmoore 'docker: add docker-compose installation to the role'
    - ansible/roles/docker/tasks/docker-common.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#639](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/639/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/639/consoleText) for more details.
Possible conflicts:
  - PR #64 joshmoore 'docker: add docker-compose installation to the role'
    - ansible/roles/docker/tasks/docker-common.yml

**Comment by manics** [comment]
@joshmoore How do you want to manage this and #64?

**Pull request merged**
