### PR TITLE
virtualenv role

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
To test:

- create VM
- test.yml

 ```
- hosts: localhost, all

  roles:
  - role: python-devel


  tasks:
  - name: install python packages
    become: yes
    pip:
      name: "{{ item }}"
      extra_args: "--upgrade"
      virtualenv: "/home/centos/venv"
      virtualenv_command: "virtualenv"
      virtualenv_site_packages: "yes"
      state: latest
    with_items:
      - pip
      - setuptools
```
- run

 ```

(ansible) MacBookPro:DOCKER ola$ source ~/ome101-openrc.sh 
Please enter your OpenStack Password: 
(ansible) MacBookPro:DOCKER ola$ export ANSIBLE_ROLES_PATH=infrastructure/ansible/roles
(ansible) MacBookPro:DOCKER ola$ ansible-playbook -i infrastructure/ansible/inventory/openstack.py -l ola-test -vv -u centos infrastructure/openstack/examples/test.yml 
No config file found; using defaults

PLAYBOOK: test.yml *************************************************************
1 plays in infrastructure/openstack/examples/test.yml

PLAY [localhost, all] **********************************************************

TASK [setup] *******************************************************************
ok: [fe189ccb-a248-4600-b973-e39370c7bc3e]

TASK [python-devel : system packages | install epel repo] **********************
task path: /Users/ola/OMERO/DOCKER/infrastructure/ansible/roles/python-devel/tasks/main.yml:4
changed: [fe189ccb-a248-4600-b973-e39370c7bc3e] => {"changed": true, "msg": "warning: /var/cache/yum/x86_64/7/extras/packages/epel-release-7-6.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY\nImporting GPG key 0xF4A80EB5:\n Userid     : \"CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>\"\n Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5\n Package    : centos-release-7-2.1511.el7.centos.2.10.x86_64 (installed)\n From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7\n", "rc": 0, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: mirror.bytemark.co.uk\n * extras: mirror.vorboss.net\n * updates: mirrors.melbourne.co.uk\nResolving Dependencies\n--> Running transaction check\n---> Package epel-release.noarch 0:7-6 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package                Arch             Version         Repository        Size\n================================================================================\nInstalling:\n epel-release           noarch           7-6             extras            14 k\n\nTransaction Summary\n================================================================================\nInstall  1 Package\n\nTotal download size: 14 k\nInstalled size: 24 k\nDownloading packages:\nPublic key for epel-release-7-6.noarch.rpm is not installed\nRetrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7\nRunning transaction check\nRunning transaction test\nTransaction test succeeded\nRunning transaction\n  Installing : epel-release-7-6.noarch                                      1/1 \n  Verifying  : epel-release-7-6.noarch                                      1/1 \n\nInstalled:\n  epel-release.noarch 0:7-6                                                     \n\nComplete!\n"]}

TASK [python-devel : install python-devel] *************************************
task path: /Users/ola/OMERO/DOCKER/infrastructure/ansible/roles/python-devel/tasks/main.yml:10
changed: [fe189ccb-a248-4600-b973-e39370c7bc3e] => (item=[u'python-devel', u'gcc']) => {"changed": true, "item": ["python-devel", "gcc"], "msg": "", "rc": 0, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: mirror.bytemark.co.uk\n * epel: mirror.bytemark.co.uk\n * extras: mirror.vorboss.net\n * updates: mirrors.melbourne.co.uk\nResolving Dependencies\n--> Running transaction check\n---> Package gcc.x86_64 0:4.8.5-4.el7 will be installed\n--> Processing Dependency: cpp = 4.8.5-4.el7 for package: gcc-4.8.5-4.el7.x86_64\n--> Processing Dependency: glibc-devel >= 2.2.90-12 for package: gcc-4.8.5-4.el7.x86_64\n--> Processing Dependency: libmpfr.so.4()(64bit) for package: gcc-4.8.5-4.el7.x86_64\n--> Processing Dependency: libmpc.so.3()(64bit) for package: gcc-4.8.5-4.el7.x86_64\n---> Package python-devel.x86_64 0:2.7.5-34.el7 will be installed\n--> Running transaction check\n---> Package cpp.x86_64 0:4.8.5-4.el7 will be installed\n---> Package glibc-devel.x86_64 0:2.17-106.el7_2.8 will be installed\n--> Processing Dependency: glibc-headers = 2.17-106.el7_2.8 for package: glibc-devel-2.17-106.el7_2.8.x86_64\n--> Processing Dependency: glibc = 2.17-106.el7_2.8 for package: glibc-devel-2.17-106.el7_2.8.x86_64\n--> Processing Dependency: glibc-headers for package: glibc-devel-2.17-106.el7_2.8.x86_64\n---> Package libmpc.x86_64 0:1.0.1-3.el7 will be installed\n---> Package mpfr.x86_64 0:3.1.1-4.el7 will be installed\n--> Running transaction check\n---> Package glibc.x86_64 0:2.17-106.el7_2.6 will be updated\n--> Processing Dependency: glibc = 2.17-106.el7_2.6 for package: glibc-common-2.17-106.el7_2.6.x86_64\n---> Package glibc.x86_64 0:2.17-106.el7_2.8 will be an update\n---> Package glibc-headers.x86_64 0:2.17-106.el7_2.8 will be installed\n--> Processing Dependency: kernel-headers >= 2.2.1 for package: glibc-headers-2.17-106.el7_2.8.x86_64\n--> Processing Dependency: kernel-headers for package: glibc-headers-2.17-106.el7_2.8.x86_64\n--> Running transaction check\n---> Package glibc-common.x86_64 0:2.17-106.el7_2.6 will be updated\n---> Package glibc-common.x86_64 0:2.17-106.el7_2.8 will be an update\n---> Package kernel-headers.x86_64 0:3.10.0-327.28.2.el7 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package             Arch        Version                     Repository    Size\n================================================================================\nInstalling:\n gcc                 x86_64      4.8.5-4.el7                 base          16 M\n python-devel        x86_64      2.7.5-34.el7                base         391 k\nInstalling for dependencies:\n cpp                 x86_64      4.8.5-4.el7                 base         5.9 M\n glibc-devel         x86_64      2.17-106.el7_2.8            updates      1.0 M\n glibc-headers       x86_64      2.17-106.el7_2.8            updates      663 k\n kernel-headers      x86_64      3.10.0-327.28.2.el7         updates      3.2 M\n libmpc              x86_64      1.0.1-3.el7                 base          51 k\n mpfr                x86_64      3.1.1-4.el7                 base         203 k\nUpdating for dependencies:\n glibc               x86_64      2.17-106.el7_2.8            updates      3.6 M\n glibc-common        x86_64      2.17-106.el7_2.8            updates       11 M\n\nTransaction Summary\n================================================================================\nInstall  2 Packages (+6 Dependent packages)\nUpgrade             ( 2 Dependent packages)\n\nTotal download size: 43 M\nDownloading packages:\nDelta RPMs disabled because /usr/bin/applydeltarpm not installed.\n--------------------------------------------------------------------------------\nTotal                                               11 MB/s |  43 MB  00:03     \nRunning transaction check\nRunning transaction test\nTransaction test succeeded\nRunning transaction\n  Updating   : glibc-2.17-106.el7_2.8.x86_64                               1/12 \n  Updating   : glibc-common-2.17-106.el7_2.8.x86_64                        2/12 \n  Installing : mpfr-3.1.1-4.el7.x86_64                                     3/12 \n  Installing : libmpc-1.0.1-3.el7.x86_64                                   4/12 \n  Installing : cpp-4.8.5-4.el7.x86_64                                      5/12 \n  Installing : kernel-headers-3.10.0-327.28.2.el7.x86_64                   6/12 \n  Installing : glibc-headers-2.17-106.el7_2.8.x86_64                       7/12 \n  Installing : glibc-devel-2.17-106.el7_2.8.x86_64                         8/12 \n  Installing : gcc-4.8.5-4.el7.x86_64                                      9/12 \n  Installing : python-devel-2.7.5-34.el7.x86_64                           10/12 \n  Cleanup    : glibc-2.17-106.el7_2.6.x86_64                              11/12 \n  Cleanup    : glibc-common-2.17-106.el7_2.6.x86_64                       12/12 \n  Verifying  : python-devel-2.7.5-34.el7.x86_64                            1/12 \n  Verifying  : gcc-4.8.5-4.el7.x86_64                                      2/12 \n  Verifying  : cpp-4.8.5-4.el7.x86_64                                      3/12 \n  Verifying  : glibc-devel-2.17-106.el7_2.8.x86_64                         4/12 \n  Verifying  : mpfr-3.1.1-4.el7.x86_64                                     5/12 \n  Verifying  : glibc-headers-2.17-106.el7_2.8.x86_64                       6/12 \n  Verifying  : libmpc-1.0.1-3.el7.x86_64                                   7/12 \n  Verifying  : glibc-common-2.17-106.el7_2.8.x86_64                        8/12 \n  Verifying  : glibc-2.17-106.el7_2.8.x86_64                               9/12 \n  Verifying  : kernel-headers-3.10.0-327.28.2.el7.x86_64                  10/12 \n  Verifying  : glibc-common-2.17-106.el7_2.6.x86_64                       11/12 \n  Verifying  : glibc-2.17-106.el7_2.6.x86_64                              12/12 \n\nInstalled:\n  gcc.x86_64 0:4.8.5-4.el7          python-devel.x86_64 0:2.7.5-34.el7         \n\nDependency Installed:\n  cpp.x86_64 0:4.8.5-4.el7                                                      \n  glibc-devel.x86_64 0:2.17-106.el7_2.8                                         \n  glibc-headers.x86_64 0:2.17-106.el7_2.8                                       \n  kernel-headers.x86_64 0:3.10.0-327.28.2.el7                                   \n  libmpc.x86_64 0:1.0.1-3.el7                                                   \n  mpfr.x86_64 0:3.1.1-4.el7                                                     \n\nDependency Updated:\n  glibc.x86_64 0:2.17-106.el7_2.8     glibc-common.x86_64 0:2.17-106.el7_2.8    \n\nComplete!\n"]}

TASK [python-devel : virtualenv | install python tools] ************************
task path: /Users/ola/OMERO/DOCKER/infrastructure/ansible/roles/python-devel/tasks/main.yml:19
changed: [fe189ccb-a248-4600-b973-e39370c7bc3e] => (item=[u'python-pip', u'python-setuptools', u'python-virtualenv']) => {"changed": true, "item": ["python-pip", "python-setuptools", "python-virtualenv"], "msg": "warning: /var/cache/yum/x86_64/7/epel/packages/python-pip-7.1.0-1.el7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY\nImporting GPG key 0x352C64E5:\n Userid     : \"Fedora EPEL (7) <epel@fedoraproject.org>\"\n Fingerprint: 91e9 7d7c 4a5e 96f1 7f3e 888f 6a2f aea2 352c 64e5\n Package    : epel-release-7-6.noarch (@extras)\n From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7\n", "rc": 0, "results": ["python-setuptools-0.9.8-4.el7.noarch providing python-setuptools is already installed", "Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: mirror.bytemark.co.uk\n * epel: mirror.bytemark.co.uk\n * extras: mirror.vorboss.net\n * updates: mirrors.melbourne.co.uk\nResolving Dependencies\n--> Running transaction check\n---> Package python-pip.noarch 0:7.1.0-1.el7 will be installed\n---> Package python-virtualenv.noarch 0:1.10.1-2.el7 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package                  Arch          Version               Repository   Size\n================================================================================\nInstalling:\n python-pip               noarch        7.1.0-1.el7           epel        1.5 M\n python-virtualenv        noarch        1.10.1-2.el7          base        1.2 M\n\nTransaction Summary\n================================================================================\nInstall  2 Packages\n\nTotal download size: 2.8 M\nInstalled size: 8.1 M\nDownloading packages:\nPublic key for python-pip-7.1.0-1.el7.noarch.rpm is not installed\n--------------------------------------------------------------------------------\nTotal                                              5.2 MB/s | 2.8 MB  00:00     \nRetrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7\nRunning transaction check\nRunning transaction test\nTransaction test succeeded\nRunning transaction\n  Installing : python-virtualenv-1.10.1-2.el7.noarch                        1/2 \n  Installing : python-pip-7.1.0-1.el7.noarch                                2/2 \n  Verifying  : python-pip-7.1.0-1.el7.noarch                                1/2 \n  Verifying  : python-virtualenv-1.10.1-2.el7.noarch                        2/2 \n\nInstalled:\n  python-pip.noarch 0:7.1.0-1.el7    python-virtualenv.noarch 0:1.10.1-2.el7   \n\nComplete!\n"]}

TASK [install python packages] *************************************************
task path: /Users/ola/OMERO/DOCKER/infrastructure/openstack/examples/test.yml:8
changed: [fe189ccb-a248-4600-b973-e39370c7bc3e] => (item=pip) => {"changed": true, "cmd": "/home/centos/venv/bin/pip install -U --upgrade pip", "item": "pip", "name": "pip", "requirements": null, "state": "latest", "stderr": "", "stdout": "New python executable in /home/centos/venv/bin/python\nInstalling Setuptools..............................................................................................................................................................................................................................done.\nInstalling Pip.....................................................................................................................................................................................................................................................................................................................................done.\nDownloading/unpacking pip from https://pypi.python.org/packages/e7/a8/7556133689add8d1a54c0b14aeff0acb03c64707ce100ecd53934da1aa13/pip-8.1.2.tar.gz#md5=87083c0b9867963b29f7aba3613e8f4a\n  Running setup.py egg_info for package pip\n    \n    warning: no previously-included files found matching '.coveragerc'\n    warning: no previously-included files found matching '.mailmap'\n    warning: no previously-included files found matching '.travis.yml'\n    warning: no previously-included files found matching '.landscape.yml'\n    warning: no previously-included files found matching 'pip/_vendor/Makefile'\n    warning: no previously-included files found matching 'tox.ini'\n    warning: no previously-included files found matching 'dev-requirements.txt'\n    warning: no previously-included files found matching 'appveyor.yml'\n    no previously-included directories found matching '.github'\n    no previously-included directories found matching '.travis'\n    no previously-included directories found matching 'docs/_build'\n    no previously-included directories found matching 'contrib'\n    no previously-included directories found matching 'tasks'\n    no previously-included directories found matching 'tests'\nInstalling collected packages: pip\n  Found existing installation: pip 1.4.1\n    Uninstalling pip:\n      Successfully uninstalled pip\n  Running setup.py install for pip\n    \n    warning: no previously-included files found matching '.coveragerc'\n    warning: no previously-included files found matching '.mailmap'\n    warning: no previously-included files found matching '.travis.yml'\n    warning: no previously-included files found matching '.landscape.yml'\n    warning: no previously-included files found matching 'pip/_vendor/Makefile'\n    warning: no previously-included files found matching 'tox.ini'\n    warning: no previously-included files found matching 'dev-requirements.txt'\n    warning: no previously-included files found matching 'appveyor.yml'\n    no previously-included directories found matching '.github'\n    no previously-included directories found matching '.travis'\n    no previously-included directories found matching 'docs/_build'\n    no previously-included directories found matching 'contrib'\n    no previously-included directories found matching 'tasks'\n    no previously-included directories found matching 'tests'\n    Installing pip script to /home/centos/venv/bin\n    Installing pip2.7 script to /home/centos/venv/bin\n    Installing pip2 script to /home/centos/venv/bin\nSuccessfully installed pip\nCleaning up...\n", "stdout_lines": ["New python executable in /home/centos/venv/bin/python", "Installing Setuptools..............................................................................................................................................................................................................................done.", "Installing Pip.....................................................................................................................................................................................................................................................................................................................................done.", "Downloading/unpacking pip from https://pypi.python.org/packages/e7/a8/7556133689add8d1a54c0b14aeff0acb03c64707ce100ecd53934da1aa13/pip-8.1.2.tar.gz#md5=87083c0b9867963b29f7aba3613e8f4a", "  Running setup.py egg_info for package pip", "    ", "    warning: no previously-included files found matching '.coveragerc'", "    warning: no previously-included files found matching '.mailmap'", "    warning: no previously-included files found matching '.travis.yml'", "    warning: no previously-included files found matching '.landscape.yml'", "    warning: no previously-included files found matching 'pip/_vendor/Makefile'", "    warning: no previously-included files found matching 'tox.ini'", "    warning: no previously-included files found matching 'dev-requirements.txt'", "    warning: no previously-included files found matching 'appveyor.yml'", "    no previously-included directories found matching '.github'", "    no previously-included directories found matching '.travis'", "    no previously-included directories found matching 'docs/_build'", "    no previously-included directories found matching 'contrib'", "    no previously-included directories found matching 'tasks'", "    no previously-included directories found matching 'tests'", "Installing collected packages: pip", "  Found existing installation: pip 1.4.1", "    Uninstalling pip:", "      Successfully uninstalled pip", "  Running setup.py install for pip", "    ", "    warning: no previously-included files found matching '.coveragerc'", "    warning: no previously-included files found matching '.mailmap'", "    warning: no previously-included files found matching '.travis.yml'", "    warning: no previously-included files found matching '.landscape.yml'", "    warning: no previously-included files found matching 'pip/_vendor/Makefile'", "    warning: no previously-included files found matching 'tox.ini'", "    warning: no previously-included files found matching 'dev-requirements.txt'", "    warning: no previously-included files found matching 'appveyor.yml'", "    no previously-included directories found matching '.github'", "    no previously-included directories found matching '.travis'", "    no previously-included directories found matching 'docs/_build'", "    no previously-included directories found matching 'contrib'", "    no previously-included directories found matching 'tasks'", "    no previously-included directories found matching 'tests'", "    Installing pip script to /home/centos/venv/bin", "    Installing pip2.7 script to /home/centos/venv/bin", "    Installing pip2 script to /home/centos/venv/bin", "Successfully installed pip", "Cleaning up..."], "version": null, "virtualenv": "/home/centos/venv"}
changed: [fe189ccb-a248-4600-b973-e39370c7bc3e] => (item=setuptools) => {"changed": true, "cmd": "/home/centos/venv/bin/pip install -U --upgrade setuptools", "item": "setuptools", "name": "setuptools", "requirements": null, "state": "latest", "stderr": "", "stdout": "Collecting setuptools\n  Downloading setuptools-25.2.0-py2.py3-none-any.whl (442kB)\nInstalling collected packages: setuptools\n  Found existing installation: setuptools 0.9.8\n    Uninstalling setuptools-0.9.8:\n      Successfully uninstalled setuptools-0.9.8\nSuccessfully installed setuptools-25.2.0\n", "stdout_lines": ["Collecting setuptools", "  Downloading setuptools-25.2.0-py2.py3-none-any.whl (442kB)", "Installing collected packages: setuptools", "  Found existing installation: setuptools 0.9.8", "    Uninstalling setuptools-0.9.8:", "      Successfully uninstalled setuptools-0.9.8", "Successfully installed setuptools-25.2.0"], "version": null, "virtualenv": "/home/centos/venv"}

PLAY RECAP *********************************************************************
fe189ccb-a248-4600-b973-e39370c7bc3e : ok=5    changed=4    unreachable=0    failed=0 



(ansible) MacBookPro:DOCKER ola$ ssh centos@10.0.51.137
Warning: Permanently added '10.0.51.137' (ECDSA) to the list of known hosts.
Last login: Mon Aug 15 15:05:35 2016 from 134.36.162.152
[centos@ola-test ~]$ pip --version
pip 7.1.0 from /usr/lib/python2.7/site-packages (python 2.7)
[centos@ola-test ~]$ source venv/bin/activate
(venv)[centos@ola-test ~]$  pip --version
pip 8.1.2 from /home/centos/venv/lib/python2.7/site-packages (python 2.7)
(venv)[centos@ola-test ~]$ 
```

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
do we want that test as a create-venv role?

**Comment by manics** [comment]
Does it need to be in it's own role? You could merge it with the https://github.com/openmicroscopy/infrastructure/blob/master/ansible/roles/python-devel/tasks/main.yml role (or merge that into this one?)

**Comment by aleksandra-tarkowska** [comment]
Done

**Comment by manics** [comment]
👍

**Pull request merged**
