### PR TITLE
Openstack playbooks multivm

### PR DESCRIPTION
**Pull request by manics**
Latest IDR deployment playbook, including changes to some roles.

Includes:
- https://github.com/openmicroscopy/infrastructure/pull/72 Nginx proxy changes
- https://github.com/openmicroscopy/infrastructure/pull/75 Allow external connections to postgresql server
- https://github.com/openmicroscopy/infrastructure/pull/63 OMERO log-monitoring role

There's more that could be split out of this PR

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#691](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/691/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/691/consoleText) for more details.
Possible conflicts:
  - PR #75 manics 'Allow external connections to postgresql server'
    - ansible/roles/postgresql/README.md
    - ansible/roles/postgresql/handlers/main.yml
    - ansible/roles/postgresql/defaults/main.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#692](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/692/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/692/consoleText) for more details.
Possible conflicts:
  - PR #75 manics 'Allow external connections to postgresql server'
    - ansible/roles/postgresql/README.md
    - ansible/roles/postgresql/handlers/main.yml
    - ansible/roles/postgresql/defaults/main.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#693](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/693/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/693/consoleText) for more details.
Possible conflicts:
  - PR #75 manics 'Allow external connections to postgresql server'
    - ansible/roles/postgresql/README.md
    - ansible/roles/postgresql/handlers/main.yml
    - ansible/roles/postgresql/defaults/main.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#694](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/694/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/694/consoleText) for more details.
Possible conflicts:
  - PR #75 manics 'Allow external connections to postgresql server'
    - ansible/roles/postgresql/README.md
    - ansible/roles/postgresql/handlers/main.yml
    - ansible/roles/postgresql/defaults/main.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#695](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/695/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/695/consoleText) for more details.
Possible conflicts:
  - PR #75 manics 'Allow external connections to postgresql server'
    - ansible/roles/postgresql/README.md
    - ansible/roles/postgresql/handlers/main.yml
    - ansible/roles/postgresql/defaults/main.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#696](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/696/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/696/consoleText) for more details.
Possible conflicts:
  - PR #75 manics 'Allow external connections to postgresql server'
    - ansible/roles/postgresql/README.md
    - ansible/roles/postgresql/handlers/main.yml
    - ansible/roles/postgresql/defaults/main.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#697](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/697/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/697/consoleText) for more details.
Possible conflicts:
  - PR #75 manics 'Allow external connections to postgresql server'
    - ansible/roles/postgresql/README.md
    - ansible/roles/postgresql/handlers/main.yml
    - ansible/roles/postgresql/defaults/main.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#698](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/698/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/698/consoleText) for more details.
Possible conflicts:
  - PR #75 manics 'Allow external connections to postgresql server'
    - ansible/roles/postgresql/README.md
    - ansible/roles/postgresql/handlers/main.yml
    - ansible/roles/postgresql/defaults/main.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#699](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/699/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/699/consoleText) for more details.
Possible conflicts:
  - PR #75 manics 'Allow external connections to postgresql server'
    - ansible/roles/postgresql/README.md
    - ansible/roles/postgresql/handlers/main.yml
    - ansible/roles/postgresql/defaults/main.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#700](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/700/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/700/consoleText) for more details.
Possible conflicts:
  - PR #75 manics 'Allow external connections to postgresql server'
    - ansible/roles/postgresql/README.md
    - ansible/roles/postgresql/handlers/main.yml
    - ansible/roles/postgresql/defaults/main.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#701](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/701/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/701/consoleText) for more details.
Possible conflicts:
  - PR #75 manics 'Allow external connections to postgresql server'
    - ansible/roles/postgresql/README.md
    - ansible/roles/postgresql/handlers/main.yml
    - ansible/roles/postgresql/defaults/main.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#702](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/702/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/702/consoleText) for more details.
Possible conflicts:
  - PR #75 manics 'Allow external connections to postgresql server'
    - ansible/roles/postgresql/README.md
    - ansible/roles/postgresql/handlers/main.yml
    - ansible/roles/postgresql/defaults/main.yml

**Comment by joshmoore** [comment]
Closed the PRs listed in the description in favor of this PR. I'm going to do a final read-through and then merge as the most accurate (even if confusing) state of IDR-0.0.5. Speak up if there are any objections.

**Comment by joshmoore** [comment]
Merging to tag as IDR-0.0.5. @manics will look into fixing the vdb1/vdb issue

**Pull request merged**
