### PR TITLE
add system-monitor-agent to idr-openstack-post

### PR DESCRIPTION
**Pull request by kennethgillen**
An attempt to get OpenStack hosts monitored, ref https://trello.com/c/I44vjgMn/2734-idr3-slot-12-check-mk-agent

to match https://github.com/openmicroscopy/ansible-role-system-monitor-agent/pull/1/files

## Added 2017-03-09
--depends-on https://github.com/openmicroscopy/ansible-role-system-monitor-agent/pull/1

### CODE REVIEW

**Comment by manics** [comment]
Unfortunately it's not that easy, you'll need to delete https://github.com/openmicroscopy/infrastructure/tree/master/ansible/roles/system-monitor-agent and add https://github.com/openmicroscopy/ansible-role-system-monitor-agent to a requirements file, probably a separate internal-only one.

**Comment by joshmoore** [comment]
@manics can you propose a chance to make this work?

**Comment by manics** [comment]
The added commits:
- Updates the role requirements
- Installs `check-mk-agent-1.2.6p16-3.el7.x86_64`
- Creates a MySQL backup cron job

**Comment by kennethgillen** [comment]
I'd love to follow this up with 
 * xinetd.conf
 * `logwatch` plugin configuration

**Comment by joshmoore** [comment]
Restarted travis.

**Comment by joshmoore** [comment]
Travis failed again (different error), @manics:

```
The offending line appears to be:

    - role: versioncontrol-utils
    - role: system-monitor-agent
      ^ here
```

**Comment by manics** [comment]
Fixed by the last commit.

**Comment by joshmoore** [comment]
Merging as green. The only thing I'd suggest is that once @kennethgillen is back, we migrate his repo to the org under the general rule "_minimize the time (zero is optimal) that a merge org commit depends on a non-org commit or repo_"

**Comment by manics** [comment]
Which repo?

**Comment by joshmoore** [comment]
https://github.com/openmicroscopy/infrastructure/pull/250/files#diff-be480e038f2b7020812ab8b548380659R7 or at least to migrate the branch.

**Comment by manics** [comment]
Good point... it's waiting on https://github.com/openmicroscopy/ansible-role-system-monitor-agent/pull/1

**Pull request merged**
