### PR TITLE
upgrade mapr

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
https://trello.com/c/pXYGqQqq/80-upgrade-mapr-to-0-1-7

### CODE REVIEW

**Comment by joshmoore** [comment]
Leaving @manics to comment. This might conflict with his mega branch.

**Comment by aleksandra-tarkowska** [comment]
@manics feel free to update in any of your PRs and close this one

**Comment by manics** [comment]
It' s cherry-picked into my https://github.com/manics/infrastructure/tree/idr-0-3-0 branch, I'll leave this on-hold till it's finally all emrged.

**Comment by manics** [comment]
--exclude

**Comment by manics** [comment]
Cherry-picked to https://github.com/openmicroscopy/infrastructure/pull/194

**Pull request closed without merging**
