### PR TITLE
Capture Ansible requirements in requirements.txt

### PR DESCRIPTION
**Pull request by sbesson**
While trying to initiate a VM on an OpenStack instance, I encountered https://groups.google.com/forum/#!msg/ansible-project/3pj7jknSqd8/cr4Zt6L2BQAJ.

Rather than hardcoding the version in various places in the documentation, this PR migrates all the Python dependencies into a top-level `requirements.txt` as we do for any Python app. Dependencies can be pinned and upgraded via PR.

Travis is also updated to consume the requirements file.

### CODE REVIEW

**Comment by manics** [comment]
How did you get that error? The latest shade works for me:
```
$ pip show shade
Name: shade
Version: 1.13.2
```

**Comment by sbesson** [comment]
````
(ansible) sbesson@lifesci-56045:ansible ((b5b15ca...)) $ ansible-playbook -e vm_key_name=seb-dundee -e vm_name=www-dev os-uod-web.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [fail] ********************************************************************
skipping: [localhost]

TASK [fail] ********************************************************************
skipping: [localhost]

TASK [Web external access security group] **************************************
ok: [localhost]

TASK [Web external access security group rules] ********************************
ok: [localhost] => (item=22)
ok: [localhost] => (item=80)
ok: [localhost] => (item=443)

TASK [Web VM] ******************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": null, "failed": true, "msg": "Error in creating instance (Inner Exception: create() takes at least 4 arguments (9 given))"}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1   
```

**Comment by joshmoore** [comment]
@sbesson to test via gh-228

**Comment by sbesson** [comment]
Retested via 1.13.2 both while creating a devspace and a Web box, I could not reproduce https://github.com/openmicroscopy/infrastructure/pull/231#issuecomment-268252442. I suspect this has to do with my own configuration files that I had to fix post OS reinstallation. I'll push an extra commit to pin shade to 1.13.2

**Comment by sbesson** [comment]
Note while testing the devspace deployment with Ansible 2.2.0, I faced two issues:
- https://github.com/ansible/ansible-modules-core/issues/5504
- https://github.com/ansible/ansible/issues/18357

Downgraded Ansible to 2.1.3.0 in the meantime, I propose to update https://github.com/openmicroscopy/infrastructure/pull/231 accordingly.

**Comment by sbesson** [comment]
Pushed the requirements I used for testing gh-228

**Comment by joshmoore** [comment]
Merging with travis green. There's a broader story here to be looked into in the new year.

**Pull request merged**
