### PR TITLE
Split deployment playbooks

### PR DESCRIPTION
**Pull request by sbesson**
- OMERO and Documentation prerequisites are moved to their own playbooks
- jenkinsslave and version control are moved to the CI deployment playbook

Follows #28

### CODE REVIEW

**Comment by sbesson** [comment]
Will investigate the one vs many playbooks with one vs many hosts.

**Comment by sbesson** [comment]
@manics @joshmoore @kennethgillen: last commit should keep a single CI playbook with multiple target groups (to be defined in the inventories)

**Comment by manics** [comment]
Looks fine to me (though I haven't tested it yet)

**Comment by joshmoore** [comment]
In terms of naming:

 * "ci-omero": :thumbsup:
 * "ci-deployment": less so, but I can learn to live with it.

**Comment by joshmoore** [comment]
Friday afternoon cleanup.

**Pull request merged**
