### PR TITLE
Extract, build and Install GPFS packages

### PR DESCRIPTION
**Pull request by manics**
See ansible/roles/gpfs/README.md

Summary:

- Extracts GPFS RPMs from the distributed package
- Builds a kernel module RPM
- Downloads to the local host
- Uploads to the client servers
- Installs module
- Optional configuration

### CODE REVIEW

**Comment by manics** [comment]
I'll push the playbook after #51

**Comment by manics** [comment]
(rebased)

**Comment by manics** [comment]
Added yum exclusions to prevent unexpected kernel/systemd upgrades

**Comment by sbesson** [comment]
@joshmoore: any veto to getting this merged ?

**Comment by joshmoore** [comment]
I haven't tested, but if everyone's happy, no veto.

**Comment by joshmoore** [comment]
11 days of no vetoes seems healthy.

**Pull request merged**
