### PR TITLE
devspace playbook

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR shows how to deploy and manage devspace using ansible and docker_service

## Minimum requirements:
 - brief understanding of ansible http://docs.ansible.com/ansible/intro_getting_started.html or tutorial by @joshmoore 
  - inventory http://docs.ansible.com/ansible/intro_inventory.html
  - playbook http://docs.ansible.com/ansible/playbooks.html
 - access to openstack tenancy
 - own ssh key set in openstack tenancy, that name will be used as `vm_key_name`
 - `openrc.sh` http://docs.openstack.org/user-guide/common/cli-set-environment-variables-using-openstack-rc.html
 - snoopy ssh key and gitconfig (* to be discussed

## Deployment
To run devspace run following on the client machine:

- install virtualenv and pip prerequisites:

 ```
$ virtualenv dev
$ source dev/bin/activate
(dev) $ pip install ansible
(dev) $ pip install shade

(dev) $ git clone -b devspace https://github.com/aleksandra-tarkowska/infrastructure.git
(dev) $ cd infrastracture/ansible
```

- create vm (**boot from volume, you no longer have to attach additional volumes**)

 ```
(dev) $ source path/to/openrc.sh
# vm_key_name is a name of ssh key in openstack
# vm_size (default 50GB) is a size of the volume vm boot from. You no longer have to attach additional volumes!
(dev) $ ansible-playbook os-devspace.yml -e vm_name=my-devspace -e vm_key_name=mysshkey
```

  **write down IP of newly created vm, you will need it below to set `openstack_ip`**

- create inventory:

 ```
$ tree /path/to/inventory
devspace
      ├── devspace-hosts
      ├── group_vars
      │   └── devspace
      └── snoopy
          ├── .gitconfig
          └── .ssh

 ```

 - `/path/to/inventory/devspace/devspace-hosts`

    ```
    [devspace]
    10.0.50.100
    ```

 - put snoopy .ssh in `/path/to/inventory/devspace/snoopy/.ssh` that includes:

    ```
    -rwx------.  1    74 Sep 13 15:25 config
    -rwx------.  1  1674 Sep 13 15:25 snoopycrimecop_github
    -rwx------.  1   405 Sep 13 15:25 snoopycrimecop_github.pub
    ```

 - put snoopy gitconfig in `/path/to/inventory/devspace/snoopy/.gitconfig`

 - `/path/to/inventory/devspace/group_vars/devspace`

    ```
    docker_use_ipv4_nic_mtu: True
    devuser: omero
    user_id: "1001"
    devhome: /home/{{ devuser }}/devspace
    openstack_ip: 10.0.50.100
    omero_branch: develop
    snoopy_dir_path: "/path/to/inventory/devspace/snoopy"
    git_repo: "https://github.com/aleksandra-tarkowska/devspace.git"
    version: "round4"
    ```

- install prerequisites as default user with sudo privileges (**assume `centos`**)

 ```
(dev) ansible-playbook -i /path/to/inventory/devspace -u centos devspace.yml
```

- run devspace container (**as user `omero`**)

 ```
(dev) ansible-playbook -i /path/to/inventory/devspace -u omero devspace-runtime.yml
```

this step will take time as for the first time it has to build containers

Jenkins is on https://10.0.50.100:8443 (you have to accept self signed cert)

the same example is in README in https://github.com/openmicroscopy/devspace/pull/50

## NOTE

**there is a bug in latest docker-py**
```
fatal: [10.0.51.143]: FAILED! => {"changed": false, "failed": true, "msg": "Error: docker-py version is 1.10.2. Minimum version required is 1.7.0."}
```
At the moment we are enforcing installation of docker-py=1.9.0, see https://github.com/ansible/ansible/issues/17495

cc : @sbesson @jburel @joshmoore

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
## Q:

- Shall I add example inventory in management tools? Would that simplify deployment?
- How do we share snoopy ssh keys and gitconfig?

**Comment by joshmoore** [comment]
> Shall I add example inventory in management tools? Would that simplify deployment?

I don't think so. Why would we need an example inventory when MT has the real inventory?

> How do we share snoopy ssh keys and gitconfig?

The best suggestion I've seen so far is: http://petrovs.info/2016/01/03/Using-Ansible-with-pass/

**Comment by aleksandra-tarkowska** [comment]
@joshmoore thx will have a look

**Comment by jburel** [comment]
for reference: https://github.com/openmicroscopy/devspace/pull/50#issuecomment-247002683

**Comment by jburel** [comment]
Followed the steps above: https://10.0.51.147:8443/

**Comment by aleksandra-tarkowska** [comment]
Please note that @kennethgillen asked about hiding Jenkins behind password. The simplest is to get basic authentication as Jenkins is already behind nginx proxy. See https://github.com/openmicroscopy/infrastructure/issues/116 for reference

**Comment by joshmoore** [comment]
Merging based on testing by @sbesson and @jburel. Requires devspace 0.3.0

**Pull request merged**
