### PR TITLE
cmake 3.3.2

### PR DESCRIPTION
**Pull request by rleigh-dundee**
Bump version to 3.3.2.

### CODE REVIEW

**Comment by joshmoore** [comment]
What's the testing / rollout strategy for something like this?

**Comment by manics** [comment]
For the new IDR hardware I was thinking:
- code review
- deploy to one server
- if it fails reprovision that server from scratch
- deploy system wide

For cowfish it's a tradeoff between the "reprovision-if-it-fails" strategy vs testing. Not my call.

**Comment by rleigh-dundee** [comment]
There's no urgency for this particular one--I found my cmake Boost PR didn't make it into this release so we're waiting on the next one.  And I found a workaround in the meantime.

**Comment by rleigh-dundee** [comment]
It would be useful to have this merged and run so we can start to run bfcpp builds on centos7.

**Comment by joshmoore** [comment]
With this diff (on a merge build):

```
diff --git a/ansible/ci-provision.yml b/ansible/ci-provision.yml
index cdd914b..93456a5 100644
--- a/ansible/ci-provision.yml
+++ b/ansible/ci-provision.yml
@@ -3,8 +3,4 @@

 - hosts: ci-jenkins-linux
   roles:
-  - role: lvm-partition
-    lvm_lvname: jenkins-workdir
-    lvm_lvmount: "{{ jenkinsworkdir }}"
-    lvm_lvsize: "{{ jenkinssize }}"
-  - role: jenkinsslave
+  - role: omero-build
```

I got:

```
TASK [omero-build : cmake | symlink] *******************************************
changed: [localhost -> localhost]

TASK [omero-build : cmake | set the global path to include cmake bin] **********
changed: [localhost -> localhost]

TASK [omero-build : exe4j packages | install] **********************************
changed: [localhost -> localhost]

...

PLAY RECAP *********************************************************************
localhost                  : ok=17   changed=3    unreachable=0    failed=0
```

when running:

```
ansible-playbook -i example-hosts -u $USERNAME -b ci-provision.yml --limit localhost -c local -C
```

**Comment by joshmoore** [comment]
Executed with:

```
ansible-playbook -i example-hosts -b --ask-become-pass ci-provision.yml --limit localhost -c local
```

to get 

```
PLAY RECAP *********************************************************************
localhost                  : ok=19   changed=3    unreachable=0    failed=0
```

:+1: Propose to merge and cleanup in follow ons.

**Pull request merged**
