### PR TITLE
Add playbook for minke

### PR DESCRIPTION
**Pull request by manics**
Tell me where to put it (prod playbook file?) and I'll move it.

### CODE REVIEW

**Comment by manics** [comment]
--depends-on #32
(which is why travis failed)

**Comment by joshmoore** [comment]
Closing to re-open for travis.

**Comment by joshmoore** [comment]
See https://github.com/openmicroscopy/management_tools/pull/82#issuecomment-159395208 (:thumbsup:)

**Comment by joshmoore** [comment]
Passed testing using an internal hosts file.

**Pull request merged**
