### PR TITLE
uod-web: enable configurable re-deployments

### PR DESCRIPTION
**Pull request by joshmoore**
For example:
```
 ansible-playbook -i inventory uod-web.yml -l www-dev -e dev_site_account=joshmoore -e dev_site_branch=master  -t quickdeploy
```

### CODE REVIEW

**Comment by sbesson** [comment]
Works for me

**Comment by joshmoore** [comment]
Thoughts on the tag strategy? Would it be better to extract this to a subplaybook?

**Comment by sbesson** [comment]
```
(ansible) sbesson@ls30630:ansible ((89d800c...)) $ time ansible-playbook -i inventory/openstack.py -e vm_key_name=seb-dundee -e vm_name=www-dev uod-web.yml -t quickdeploy

PLAY [OME Website Setup] *******************************************************

TASK [setup] *******************************************************************
ok: [9024a592-1b6c-446c-abe6-fbd6551dc693]

TASK [Clone www-dev.openmicroscopy.org source code repository] *****************
ok: [9024a592-1b6c-446c-abe6-fbd6551dc693]

TASK [Build the website using Jekyll] ******************************************
changed: [9024a592-1b6c-446c-abe6-fbd6551dc693]

TASK [Update Nginx configuration for www-dev.openmicroscopy.org] ***************
ok: [9024a592-1b6c-446c-abe6-fbd6551dc693]

PLAY RECAP *********************************************************************
9024a592-1b6c-446c-abe6-fbd6551dc693 : ok=4    changed=1    unreachable=0    failed=0   


real	0m13.514s
user	0m2.519s
sys	0m0.825s
```

so everything works as expected. With regard to tags, it is nice. But my feeling is that trying to maintain it in a complex playbook will not scale. Instead we might work towards extraction the sections of the playbook using `include` or even `role` first and then annotate these with tags in the playbook (http://goodcode.io/articles/ansible-tips/)

**Comment by joshmoore** [comment]
Currently works as advertised in the training doc. Merging. Primary RFE is to remove the dependency on the jenkins key.

**Pull request merged**
