### PR TITLE
Postgres yum repo rpms have been updated

### PR DESCRIPTION
**Pull request by manics**
The rpms containing the postgres yum repo configurations have changed.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#981](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/981/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/981/consoleText) for more details.
Possible conflicts:
  - PR #115 kennethgillen 'Adding PostgreSQL 9.5'
    - ansible/roles/postgresql/vars/main.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [MANAGEMENT_TOOLS-merge#982](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/982/). See the [console output](https://ci.openmicroscopy.org/job/MANAGEMENT_TOOLS-merge/982/consoleText) for more details.
Possible conflicts:
  - PR #115 kennethgillen 'Adding PostgreSQL 9.5'
    - ansible/roles/postgresql/vars/main.yml

**Comment by kennethgillen** [comment]
@manics  - why not add 9.5 while you're at it?

**Comment by joshmoore** [comment]
Old URLS are now working again. But taking the patch release is probably sensible.

**Pull request merged**
