### PR TITLE
docker: add docker-compose installation to the role

### PR DESCRIPTION
**Pull request by joshmoore**
This currently installs globally via python-pip from EPEL.

### CODE REVIEW

**Comment by joshmoore** [comment]
Force pushed the change from `docker-centos` to `docker-common`.

**Comment by joshmoore** [comment]
Running this on orca-3 resulted in:

```
orca.openmicroscopy.org    : ok=30   changed=5    unreachable=0    failed=0
```

and a docker restart:

```
^C[jamoore@orca ~]$ docker ps
CONTAINER ID        IMAGE               COMMAND                 CREATED             STATUS              PORTS                    NAMES
2e4fdbd496b4        pg_slave            "/sbin/entrypoint.sh"   12 weeks ago        Up 4 minutes        0.0.0.0:5433->5432/tcp   pg_slave_1
15c5a888783e        pg_master           "/sbin/entrypoint.sh"   12 weeks ago        Up 4 minutes        0.0.0.0:5432->5432/tcp   pg_master_1
```

(i.e. not everything came back up, but not this PRs fault)

**Comment by manics** [comment]
After some fun and games with possible conflicts between the system python modules and pip modules in hindsight I think a virtualenv is going to be safer and easier to manage.

**Comment by joshmoore** [comment]
Pushed versions to at least make this work. I'll need help reverting the state of orca-3 if we want to switch to virtualenv now.

**Comment by joshmoore** [comment]
closing to free up @manics.

**Pull request closed without merging**
