### PR TITLE
Use an external role to set up trust store

### PR DESCRIPTION
**Pull request by hajaalin**
Removes the trust store specific changes made earlier [aa0921b](https://github.com/hajaalin/infrastructure/commit/aa0921bcd86497f9a6da26a2b4ff2726bf4a59ed) .

[14cd6d3](https://github.com/hajaalin/infrastructure/commit/14cd6d39078811a1fc90f978c5aad78417b84cd4) is just an example of how to achieve the same result with
https://github.com/hajaalin/ansible-role-truststore. 
Here is the configuration for this example:
(https://github.com/hajaalin/omero-deploy-example/blob/master/inventory/group_vars/all/main.yml)

[e439ebf](https://github.com/hajaalin/infrastructure/commit/e439ebfdb42a82b915d49ed825745fa6ada4e0c9)  was necessary to make training-server.yml run on CentOS 7 in (Vagrant box 1611.01 for VirtualBox).

### CODE REVIEW

**Comment by joshmoore** [comment]
Hi @hajaalin. Except for the training playbook, all of these files have migrated (announcement forth-coming) to individual repositories (e.g. https://github.com/openmicroscopy/ansible-role-omero-server/pull/2).

Since we likely won't be configuring the generic training server for a truststore, shall we point to your repo from our documentation to your repo (github? galaxy?) as a potential add-on?

**Comment by hajaalin** [comment]
Hi @joshmoore , you could add a link to the GitHub repo https://github.com/hajaalin/ansible-role-truststore. I just added there a link to the OMERO deploy example. I'll update that example to use the new OMERO roles eventually.

**Comment by joshmoore** [comment]
@hajaalin : adding via https://github.com/openmicroscopy/infrastructure/pull/246 (work-in-progress) -- feedback on the updated ansible documentation certainly welcome.

**Comment by joshmoore** [comment]
We'll likely start advertising the new READMEs soon. Your role is listed in https://github.com/openmicroscopy/infrastructure/blob/master/ansible/README.md#from-the-community (More welcome!) And your fix in https://github.com/openmicroscopy/ansible-role-omero-server/releases/tag/1.2.1

Closing this since all the associated files have now been migrated to other repositories.

**Pull request closed without merging**
