### PR TITLE
Add choice of either Ice 3.5 or 3.6

### PR DESCRIPTION
**Pull request by manics**
This has already been run against cowfish.

### CODE REVIEW

**Comment by joshmoore** [comment]
Did @sbesson have any worries about this? Thought I heard a snippet of something.

**Comment by manics** [comment]
Apparently it wasn't needed, but we'll want it at some point.

**Comment by sbesson** [comment]
As @manics said, it is not needed immediately (but was tested since Ice 3.6 was installed and had to be reverted to install Ice 3.5). Since the plan is to go through a clean reinstall of cowfish at some point, could we push an extra commit to change the default back to 3.5 for `ci-deployment.yml`?

**Comment by manics** [comment]
Oops, I made the 3.5 change but got distracted

**Comment by sbesson** [comment]
Tested by removing the Ice packages and the repo on cowfish, running ansible-playbook with the current state of the PR and re-deploying a server (https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-Python27-merge-deploy/17/console). Will merge this once Travis is green.

**Pull request merged**
